name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  execute-tests:
    name: Checkout and execute tests
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4      
      - name: Execute tests
        run: |
            yarn install
            yarn test
      - name: Run CTRF annotations
        run: npx github-actions-ctrf reports/report.json
        if: always()